# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5639ed8719e6b5c50420fffb5366ffae38f62f632d2ec51dd34c88a8dd9dca8f686c5234fb5c3be2381a51a8f339b81d78c1b3cf50f56a6888e19a7ab643eef2

test:
  secret_key_base: 9acbe71e658cad9a579c8e249a773a9f9a4210ebcabcde3817e27749a89bac25ebdde96d7217e0697cbd6268ce4a33c41d6fe4d16a2a7391e9b5627d024135d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
